import json
import os

def evaluate_completion(
    completion: str,
    target: str,
    case_sensitive: bool = False,
) -> bool:

    target_list = [t.strip() for t in target.split(',')]
    

    test_str = completion.strip()

    if not case_sensitive:
        test_str = test_str.lower()
        target_list = [t.lower() for t in target_list]
    
    return any([sub_target in test_str for sub_target in target_list])

def calculate_accuracy(generated_answers_file: str, ground_truth_file: str):
    """
    Main function used to load data, compare answers, and calculate the final accuracy.
    """
    print(f"--- Starting evaluation ---")
    print(f"Model answer file: {generated_answers_file}")
    print(f"Ground-truth answer file: {ground_truth_file}")

    if not os.path.exists(generated_answers_file):
        print(f"Error: Cannot find the model-generated answer file '{generated_answers_file}'")
        return

    with open(generated_answers_file, 'r', encoding='utf-8') as f:
        generated_answers = [line.strip() for line in f]

    if not os.path.exists(ground_truth_file):
        print(f"Error: Cannot find the ground-truth answer file '{ground_truth_file}'")
        return
        
    with open(ground_truth_file, 'r', encoding='utf-8') as f:
        ground_truth_data = json.load(f)
        ground_truth_answers = [item['completion'] for item in ground_truth_data]

    if len(generated_answers) != len(ground_truth_answers):
        print("\nWarning: The number of model-generated answers ({}) does not match the number of ground-truth answers ({})!".format(
            len(generated_answers), len(ground_truth_answers)
        ))
        print("Only the shared portion of the two files will be evaluated.")
        min_len = min(len(generated_answers), len(ground_truth_answers))
        generated_answers = generated_answers[:min_len]
        ground_truth_answers = ground_truth_answers[:min_len]

    if not generated_answers:
        print("Error: No answers could be loaded for evaluation.")
        return

    correct_count = 0
    total_count = len(generated_answers)
    
    print("\n--- Starting answer-by-answer comparison ---")
    for i, (gen_ans, truth_ans) in enumerate(zip(generated_answers, ground_truth_answers)):
        is_correct = evaluate_completion(gen_ans, truth_ans)
        if is_correct:
            correct_count += 1
        if i < 5:
            print(f"Sample {i+1}:")
            print(f"  Model answer: '{gen_ans}'")
            print(f"  Ground-truth answer: '{truth_ans}'")
            print(f"  Evaluation result: {'Correct' if is_correct else 'Incorrect'}")
            print("-" * 20)

    accuracy = (correct_count / total_count) * 100 if total_count > 0 else 0
    
    print("\n--- Evaluation completed ---")
    print(f"Total evaluated samples: {total_count}")
    print(f"Number of correctly answered samples: {correct_count}")
    print(f"Final accuracy: {accuracy:.2f}%")

if __name__ == "__main__":
    # 1. Please change the first filename here to the answer file generated by your LLaDA model.
    #    For example, if you are processing qa_positive_negative_questions.txt,
    #    then the generated filename may be "answers_qa_positive_negative_questions.txt"
    GENERATED_ANSWERS_FILE = "answers_qa_positive_positive_prompt_questions.txt" 
    
    # 2. Please change the second filename here to the original JSON filename you uploaded that contains the ground-truth answers.
    GROUND_TRUTH_JSON_FILE = "qa_positive_positive_ground_truth.json"


    calculate_accuracy(GENERATED_ANSWERS_FILE, GROUND_TRUTH_JSON_FILE)
